project:
  type: website
  output-dir: _site
  resources:
    - assets/
    - obis_nodes_map.js

license:
  type: "CC BY-NC"
  text: "CC BY-NC 4.0"
  link: "https://creativecommons.org/licenses/by-nc/4.0/"

website:
  title: "Publishing eDNA data in OBIS"
  navbar:
    left:
      - text: "Presentation"
        href: index.qmd

format:
  revealjs:
    theme: [obis_theme.scss]
    title-slide-attributes:
      data-background-image: /assets/background-shapes.svg
      data-background-size: contain
      data-background-opacity: "0.2"
    css: [custom.css]
    lightbox: true
    transition: none
    slide-number: true
    chalkboard: true
    code-link: true
    code-tools: true
    preview-links: auto
    scrollable: false
    smaller: false
    mouse-wheel: false
    controls: true
    progress: true
    history: true
    center: true
    footer: |
      <span style="font-size: 10px;">© 2026 <a href="https://obis.org/" target="_blank"><img src="assets/IOC+OBIS_color.svg" style="height:60px; vertical-align:middle;"></a> License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a></span>
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        
